# web server
nginx:
  image: registry.cn-hangzhou.aliyuncs.com/shuhao/nginx-alpine:1
  ports:
    - "80:80"
    #- "443:443"
  volumes:
    # app
    - ./app:/usr/share/nginx/html
    # nginx configs
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
    - ./logs/nginx/:/var/log/nginx/:rw
    # certificates
    #- ./nginx/ca/server.crt/:/etc/nginx/server.crt:ro
    #- ./nginx/ca/server.key/:/etc/nginx/server.key:ro
  links:
    - fpm:__DOCKER_PHP_FPM__

# php-fpm
fpm:
  # build: ./php-fpm
  image: registry.cn-hangzhou.aliyuncs.com/shuhao/php-fpm-alpine:1
  ports:
    - "9000"
  volumes:
    - ./app:/usr/share/nginx/html
    # Your php.ini
    - ./php-fpm/php.ini-production:/usr/local/etc/php/php.ini:ro
    - ./logs/php-fpm/:/var/log/php-fpm/:rw
  # environment:
    # Set your APP env variables here:
    # - APP_KEY=
    # - DB_HOST=
    # - DB_DATABASE=
    # - DB_USERNAME=
    # - DB_PASSWORD=
  links:
    - mysql:mysql

# database
mysql:
  image: registry.cn-hangzhou.aliyuncs.com/shuhao/mysql-5.7.18:1
  ports:
    # Allow client to access 3306
    - "3307:3306"
  volumes:
    # NOTE: your data will be stored in ./mysql
    - ./mysql:/var/lib/mysql
    - ./logs/mysql/:/var/log/mysql/:rw
  environment:
    - MYSQL_ROOT_PASSWORD=123456
